spring:
  datasource:
    url: 'jdbc:oracle:thin:@//localhost:1522/TSTNDA_TAF' # for connecting through ssh tunnel
    username: delius_api_pool
    password: some-database-password

e2e:
  url: "https://delius-api.test.probation.service.justice.gov.uk"
  databaseAssert: true
  oauth:
    url: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    clientId: some-client-id
    clientSecret: some-client-secret
  offenderCrn: X009923
  provider: CRS
  team: CRSUAT
  staff: CRSUATU
  contacts:
    nsiOnly:
      type: CRS01
    nsi:
      type: CRS01
      eventId: 2500443138
    notUpdatable:
      type: ERGD
    updatable:
      type: CHVS
      outcome: ATTC
      eventId: 2500443138
    event:
      type: COTH
      eventId: 2500443138
    requirement:
      type: COTH
      eventId: 2500452238
      requirementId: 2500206720
    enforcement:
      type: CHVS
      eventId: 2500443138
      outcome: AFTA
      enforcement: ROM
    appointment:
      type: COTH
      eventId: 2500443138
      requirementId: 2500199144
    breachStart:
      type: AIBR
      eventId: 2500443138
    ftc:
      type: C084
      outcome: AFTC
      enforcement: ROM
      eventId: 2500452238
      requirementId: 2500206720
      officeLocation: CRSSHEF
    rarNsi:
      type: CRSAPT
      officeLocation: CRSSHEF
    rarRequirement:
      type: CRSAPT
      officeLocation: CRSSHEF
      eventId: 2500452250
      requirementId: 2500223138
  nsis:
    active:
      type: CRS01
      status: INPROG
      eventId: 2500443138
      requirementId: 2500199144
    terminated:
      type: CRS01
      status: INPROG
      outcome: CRS01
      eventId: 2500443138
      requirementId: 2500199144
    refer:
      type: CRS01
      status: REFER
    rar:
      type: CRS01
      status: INPROG
      eventId: 2500452250
      requirementId: 2500223138
  staffs:
    withTeam:
      firstName: Rhiannon
      lastName: Dennis
      provider: CRS
      teams:
        - CRSUAT
  teams:
    default:
      cluster: CRSUAT
      ldu: CRSUAT
      provider: CRS
      type: CRSUAT
      description: Test team
      unpaidWorkTeam: false