version: "3"

services:
  oauth:
    depends_on:
      - token-verification-api
    environment:
      SPRING_PROFILES_ACTIVE: dev-config,auth-seed,nomis-seed,token-verification
      TOKENVERIFICATION_ENDPOINT_URL: "http://token-verification-api:8080"

  redis:
    image: 'bitnami/redis:5.0'
    networks:
      - hmpps
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

  token-verification-api:
    image: quay.io/hmpps/token-verification-api:latest
    networks:
      - hmpps
    container_name: token-verification-api
    depends_on:
      - redis
      - oauth
    ports:
      - "8100:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      SPRING_PROFILES_ACTIVE: local-redis
      SPRING_REDIS_HOST: redis
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "http://oauth:9090/auth/.well-known/jwks.json"

  hmpps-delius-api:
    depends_on:
      - token-verification-api
    environment:
      TOKENVERIFICATION_API_BASE_URL: http://token-verification-api:8080
      FEATURES_TOKENVERIFICATION: "true"