version: "3"

services:
  oauth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    container_name: oauth
    ports:
      - "9090:9090"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090/auth/health" ]
    environment:
      SERVER_PORT: 9090
      SPRING_PROFILES_ACTIVE: dev,dev-config
      DELIUS_ENABLED: "false"

  hmpps-delius-api:
    build:
      context: .
    container_name: hmpps-delius-api
    networks:
      - hmpps
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: "jdbc:h2:mem:delius-api;MODE=Oracle;"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://oauth:9090/auth/.well-known/jwks.json
      FEATURES_TOKENVERIFICATION: "false"
      FEATURES_NSI_STATUS_HISTORY: "true"

networks:
  hmpps:
