spring:
  security.oauth2.resourceserver.jwt.public-key-location: classpath:local-public-key.pub

  datasource:
    url: 'jdbc:h2:file:./dev;MODE=Oracle;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=9092'
    username: sa
    password: password
  flyway:
    enabled: true
    clean-on-validation-error: true
    locations: classpath:/db/schema,classpath:/db/data
  h2.console:
    enabled: true
    path: /h2-console
  jpa.properties.hibernate.show_sql: true

logging.level.org.hibernate:
  SQL: debug

features:
  token-verification: false