version: 2.1

orbs:
  owasp: entur/owasp@0.0.10
  hmpps: ministryofjustice/hmpps@2.2
  aws-ecr: circleci/aws-ecr@6.7.0
  aws-code-deploy: circleci/aws-code-deploy@1.0.1

jobs:
  validate:
    executor: hmpps/java
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run:
          command: ./gradlew check
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - validate:
          filters:
            tags:
              ignore: /.*/
#      - aws-ecr/build-and-push-image:
#          name: build_docker
#          account-url: AWS_ECR_ACCOUNT_URL
#          aws-access-key-id: AWS_ACCESS_KEY_ID
#          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
#          create-repo: true
#          dockerfile: Dockerfile
#          path: .
#          region: AWS_REGION
#          repo: circleci-ecr-orb-demo
#          tag: "$CIRCLE_SHA1"
#          filters:
#            branches:
#              only:
#                - main
#      - hmpps/deploy_env:
#          name: deploy_dev
#          env: "dev"
#          context: hmpps-common-vars
#          filters:
#            branches:
#              only:
#                - main
#          requires:
#            - validate
#            - build_docker
#      - request-preprod-approval:
#          type: approval
#          requires:
#            - deploy_dev
#      - hmpps/deploy_env:
#          name: deploy_preprod
#          env: "preprod"
#          context:
#            - hmpps-common-vars
#            - hmpps-delius-api-preprod
#          requires:
#            - request-preprod-approval
#      - request-prod-approval:
#          type: approval
#          requires:
#            - deploy_preprod
#      - hmpps/deploy_env:
#          name: deploy_prod
#          env: "prod"
#          slack_notification: true
#          context:
#            - hmpps-common-vars
#            - hmpps-delius-api-prod
#          requires:
#            - request-prod-approval

  scheduled:
    triggers:
      - schedule:
          cron: "0 7 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - owasp/gradle_owasp_dependency_check:
          executor: hmpps/java
