version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - SPRING_PROFILES_ACTIVE=test ./gradlew e2e

reports:
  TestReport:
    base-directory: build/test-results
    files:
      - '**/*'

cache:
  paths:
    - .gradle/**/*